#!/usr/bin/env bash
name="icu"
version="72-1"
description="icu International Components for Unicode"
source="https://github.com/unicode-org/icu/releases/download/release-72-1/icu4c-72_1-src.tgz"
depends=""
group="dev.libs"


setup(){
    cd $SOURCEDIR/source
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
    chmod +x "$DESTDIR"/usr/bin/icu-config
}

