#!/usr/bin/env bash
version="1.0.8"
name="bzip2"
depends="glibc,readline,ncurses"
description="şıkıştırma kütüphanesi"
source="https://sourceware.org/pub/bzip2/${name}-${version}.tar.gz"
groups="app.arch"

setup()
{
	cd $SOURCEDIR

	# Generate relative symlinks
	sed -i \
		-e 's:\$(PREFIX)/man:\$(PREFIX)/share/man:g' \
		-e 's:ln -s -f $(PREFIX)/bin/:ln -s :' \
		Makefile

	# fixup broken version stuff
	sed -i \
		-e "s:1\.0\.4:$version:" \
		bzip2.1 bzip2.txt Makefile-libbz2_so manual.*
		
	
}
build()
{
	make -f Makefile-libbz2_so CC="gcc $CFLAGS $CPPFLAGS $LDFLAGS"
  	make bzip2 bzip2recover CC="gcc $CFLAGS $CPPFLAGS $LDFLAGS"

	 #make -f Makefile-libbz2_so all
	 #make all
}
package()
{
	cd $SOURCEDIR
	make PREFIX="$DESTDIR"/usr install
	install -dm755 "$DESTDIR"/usr/{bin,lib64,include,share/man/man1}

	install -m755 bzip2-shared "$DESTDIR"/usr/bin/bzip2
	install -m755 bzip2recover bzdiff bzgrep bzmore "$DESTDIR"/usr/bin
	ln -sf bzip2 "$DESTDIR"/usr/bin/bunzip2
	ln -sf bzip2 "$DESTDIR"/usr/bin/bzcat

	cp -a libbz2.so* "$DESTDIR"/usr/lib64
	ln -s libbz2.so.$version "$DESTDIR"/usr/lib64/libbz2.so
	ln -s libbz2.so.$version "$DESTDIR"/usr/lib64/libbz2.so.1 # For compatibility with some other distros

	install -m644 bzlib.h "$DESTDIR"/usr/include/

	install -m644 bzip2.1 "$DESTDIR"/usr/share/man/man1/
	ln -sf bzip2.1 "$DESTDIR"/usr/share/man/man1/bunzip2.1
	ln -sf bzip2.1 "$DESTDIR"/usr/share/man/man1/bzcat.1
	ln -sf bzip2.1 "$DESTDIR"/usr/share/man/man1/bzip2recover.1

	install -Dm644 bzip2.pc -t "$DESTDIR"/usr/lib64/pkgconfig
	
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64
	rm -r $DESTDIR/usr/lib
}


