// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "82b61223-cbfa-4d6f-9b37-a6d92b7a05ff");
user_pref("app.update.download.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1719386551);
user_pref("app.update.lastUpdateTime.background-update-timer", 1719386551);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1719386551);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1719386594);
user_pref("app.update.lastUpdateTime.region-update-timer", 1719386551);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1719386606);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1719386551);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1719386577);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1719386551);
user_pref("browser.aboutwelcome.didSeeFinalScreen", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{141db13a-83aa-47c3-9866-d2b901e80b4f}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.home-button.has-used", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1719386519);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 144);
user_pref("browser.newtabpage.activity-stream.impressionId", "{655ec6cb-aff3-438e-a9df-8542abd83a2f}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1719386604);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1719386652732");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1719408252732");
user_pref("browser.search.newSearchConfig.enabled", true);
user_pref("browser.search.region", "TR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20240526221752");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "www.google.com");
user_pref("browser.startup.homepage_override.buildID", "20240526221752");
user_pref("browser.startup.homepage_override.mstone", "126.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1719386604);
user_pref("browser.topsites.contile.lastFetch", 1719386605);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1719386625004");
user_pref("distribution.iniFile.exists.appversion", "126.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "TR");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "ae8d91b17f114b6d96c9ad497559ad58");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.cache.lastUpdate", 1719386578);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240526221752");
user_pref("extensions.lastAppVersion", "126.0.1");
user_pref("extensions.lastPlatformVersion", "126.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"d62ad631-9e7e-476b-8935-47d11794d9b6\",\"pictureinpicture@mozilla.org\":\"834937c3-d070-4bdf-be05-a06d7426fde8\",\"screenshots@mozilla.org\":\"9ecdc9d7-c3c2-4a1e-983d-1e5d48540f51\",\"webcompat-reporter@mozilla.org\":\"631e7239-e49d-4964-a534-04e901aec71d\",\"webcompat@mozilla.org\":\"a6dcf502-7c1f-4ccc-9cb4-135596b11f0a\",\"default-theme@mozilla.org\":\"8269b409-91f6-4639-99eb-64a8fecf06eb\",\"addons-search-detection@mozilla.com\":\"46bc8235-8e12-4efe-a0ea-5e32889d9e23\",\"google@search.mozilla.org\":\"f06a5ed8-3cde-4903-9232-ebb9f8c86940\",\"wikipedia@search.mozilla.org\":\"79787ca6-121f-4649-8f9e-935d5e5fb358\",\"bing@search.mozilla.org\":\"69f75a57-fbeb-43f0-9f44-1bf4e6ef11c7\",\"ddg@search.mozilla.org\":\"51e2293b-4245-469b-a0b8-264d5cb11282\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: null, errorCode: 5, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1719386585);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1719386585);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("memory.phc.enabled", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2024-06-26T07:23:25.400Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "a5b18404-0c47-4fbe-8fdf-8039156055d8");
user_pref("services.settings.blocklists.gfx.last_check", 1719386283);
user_pref("services.settings.clock_skew_seconds", 291);
user_pref("services.settings.last_update_seconds", 1719386283);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1719386601);
user_pref("toolkit.telemetry.cachedClientID", "a2d12d21-6e1b-4629-8cfa-34d901932231");
user_pref("toolkit.telemetry.previousBuildID", "20240526221752");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
