#!/usr/bin/env bash
version="1.3-20230209"
name="dialog"
depends="glibc,readline,ncurses"
description="shell box kütüphanesi"
source="https://invisible-island.net/archives/dialog/${name}-${version}.tgz"
groups="sys.apps"

setup()
{
	cd $SOURCEDIR
	./configure --prefix=/usr \
         --libdir=/usr/lib64/ \
         --enable-nls \
   		 --with-libtool \
         --with-ncursesw
	
}
build()
{
	make 
}
package()
{
	make install-full DESTDIR=$DESTDIR
}


